name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install build-essential
        run: |
          sudo apt update
          sudo apt install -y -q build-essential libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --all
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run fmt check
        run: cargo fmt --all -- --check
