name: Release
on:
  push:
    tags:
      - "v*" # タグが 'v' で始まる場合にトリガー
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
            suffix: "-linux"
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            extension: ".exe"
            suffix: "-windows"
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
            suffix: "-macos"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install build-essential
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y -q \
          build-essential \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Install dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Rename build artifact with OS suffix
        run: mv target/${{ matrix.target }}/release/clipboard-formatter${{ matrix.extension }} target/${{ matrix.target }}/release/clipboard-formatter${{ matrix.suffix }}${{ matrix.extension }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipboard-formatter-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/clipboard-formatter${{ matrix.suffix }}${{ matrix.extension }}
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: clipboard-formatter-ubuntu-latest
          path: artifacts/ubuntu
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: clipboard-formatter-windows-latest
          path: artifacts/windows
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: clipboard-formatter-macos-latest
          path: artifacts/macos
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/ubuntu/clipboard-formatter-linux
            artifacts/windows/clipboard-formatter-windows.exe
            artifacts/macos/clipboard-formatter-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
