name: Release
on:
  push:
    tags:
      - "v*" # タグが 'v' で始まる場合にトリガー
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            extension: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install build-essential
        run: |
          sudo apt update
          sudo apt install -y -q \
          build-essential \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          gcc-mingw-w64-x86-64
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Install dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kill-zen-all-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/kill-zen-all${{ matrix.extension }}
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
